// Auto-generated by scripts/set-env.mjs — do not edit manually.
// On Vercel: set GROQ_API_KEY in project environment variables.
// Locally: run `node scripts/set-env.mjs` to regenerate with your .env values.
export const environment = {
  production: true,
  groqApiKey: ''
};
