// Auto-generated by scripts/set-env.mjs — do not edit manually.
// Values are injected at build time from environment variables.
export const environment = {
  production: false,
  groqApiKey: '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'
};
