/**
 * set-env.mjs
 *
 * Runs before `ng build`.
 * Priority order for GROQ_API_KEY:
 *   1. process.env (Vercel sets this from Environment Variables)
 *   2. .env file (local development)
 *   3. existing environment.ts value (fallback — preserves what's already there)
 */

import { writeFileSync, mkdirSync, existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

// Step 1: Load .env file if present (local dev)
const envPath = '.env';
if (existsSync(envPath)) {
  const lines = readFileSync(envPath, 'utf8').split('\n');
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx === -1) continue;
    const key = trimmed.slice(0, eqIdx).trim();
    const val = trimmed.slice(eqIdx + 1).trim().replace(/^["']|["']$/g, '');
    if (!process.env[key]) process.env[key] = val;
  }
  console.log('[set-env] Loaded .env file');
}

// Step 2: Get key from environment
let groqApiKey = process.env['GROQ_API_KEY'] ?? '';

// Step 3: Fallback — read existing environment.ts if key is still empty
if (!groqApiKey) {
  const existingEnvPath = join('src', 'environments', 'environment.ts');
  if (existsSync(existingEnvPath)) {
    const existing = readFileSync(existingEnvPath, 'utf8');
    const match = existing.match(/groqApiKey:\s*'([^']+)'/);
    if (match?.[1]) {
      groqApiKey = match[1];
      console.log('[set-env] GROQ_API_KEY not in env — using existing value from environment.ts');
    }
  }
}

console.log('[set-env] GROQ_API_KEY present:', groqApiKey.length > 0, '| Length:', groqApiKey.length);

if (!groqApiKey) {
  console.warn('[set-env] WARNING: GROQ_API_KEY is empty! Chatbot will not work.');
}

const envDir = join('src', 'environments');
mkdirSync(envDir, { recursive: true });

const prodContent = `// Auto-generated by scripts/set-env.mjs — do not edit manually.
export const environment = {
  production: true,
  groqApiKey: '${groqApiKey}'
};
`;

const devContent = `// Auto-generated by scripts/set-env.mjs — do not edit manually.
export const environment = {
  production: false,
  groqApiKey: '${groqApiKey}'
};
`;

writeFileSync(join(envDir, 'environment.ts'), prodContent, 'utf8');
writeFileSync(join(envDir, 'environment.development.ts'), devContent, 'utf8');

console.log('[set-env] Wrote src/environments/environment.ts');
console.log('[set-env] Wrote src/environments/environment.development.ts');
