/**
 * set-env.mjs
 *
 * Runs before `ng build`.
 * Reads GROQ_API_KEY from the build environment (Vercel sets it automatically)
 * and writes both Angular environment files with the value baked in.
 */

import { writeFileSync, mkdirSync, existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

// Load .env file if present (local development only)
const envPath = '.env';
if (existsSync(envPath)) {
  const lines = readFileSync(envPath, 'utf8').split('\n');
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx === -1) continue;
    const key = trimmed.slice(0, eqIdx).trim();
    const val = trimmed.slice(eqIdx + 1).trim().replace(/^["']|["']$/g, '');
    if (!process.env[key]) process.env[key] = val;
  }
  console.log('[set-env] Loaded .env file');
} else {
  console.log('[set-env] No .env file found — using process.env (Vercel mode)');
}

const groqApiKey = process.env['GROQ_API_KEY'] ?? '';

// Log key status without exposing the full value
console.log('[set-env] GROQ_API_KEY present:', groqApiKey.length > 0, '| Length:', groqApiKey.length);

if (!groqApiKey) {
  console.warn('[set-env] WARNING: GROQ_API_KEY is empty! Chatbot will not work.');
  console.warn('[set-env] On Vercel: add GROQ_API_KEY in Project Settings → Environment Variables');
}

const envDir = join('src', 'environments');
mkdirSync(envDir, { recursive: true });

const prodContent = `// Auto-generated by scripts/set-env.mjs — do not edit manually.
export const environment = {
  production: true,
  groqApiKey: '${groqApiKey}'
};
`;

const devContent = `// Auto-generated by scripts/set-env.mjs — do not edit manually.
export const environment = {
  production: false,
  groqApiKey: '${groqApiKey}'
};
`;

writeFileSync(join(envDir, 'environment.ts'), prodContent, 'utf8');
writeFileSync(join(envDir, 'environment.development.ts'), devContent, 'utf8');

console.log('[set-env] Wrote src/environments/environment.ts');
console.log('[set-env] Wrote src/environments/environment.development.ts');
