/**
 * set-env.mjs
 *
 * Runs before `ng build` (used by build:vercel).
 * Reads environment variables from the build environment (e.g. Vercel)
 * and writes both environment files so the Angular browser bundle
 * gets the correct values baked in at compile time.
 *
 * No secrets are hardcoded — values come from the CI/CD environment.
 */

import { writeFileSync, mkdirSync, existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

// Read from process.env (Vercel sets these during build)
// Also try to load from .env file if present (local fallback)
function loadEnv() {
  const envPath = '.env';
  if (existsSync(envPath)) {
    const lines = readFileSync(envPath, 'utf8').split('\n');
    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) continue;
      const eqIdx = trimmed.indexOf('=');
      if (eqIdx === -1) continue;
      const key = trimmed.slice(0, eqIdx).trim();
      const val = trimmed.slice(eqIdx + 1).trim();
      if (!process.env[key]) process.env[key] = val;
    }
  }
}

loadEnv();

const groqApiKey = process.env['GROQ_API_KEY'] ?? '';

const envDir = join('src', 'environments');
mkdirSync(envDir, { recursive: true });

// Write production environment
const prodContent = `// Auto-generated by scripts/set-env.mjs — do not edit manually.
// Values are injected at build time from environment variables.
export const environment = {
  production: true,
  groqApiKey: '${groqApiKey}'
};
`;

// Write development environment
const devContent = `// Auto-generated by scripts/set-env.mjs — do not edit manually.
// Values are injected at build time from environment variables.
export const environment = {
  production: false,
  groqApiKey: '${groqApiKey}'
};
`;

writeFileSync(join(envDir, 'environment.ts'), prodContent, 'utf8');
writeFileSync(join(envDir, 'environment.development.ts'), devContent, 'utf8');

console.log('[set-env] Wrote src/environments/environment.ts (production)');
console.log('[set-env] Wrote src/environments/environment.development.ts (development)');
